// Converts Cormorant Garamond (SIL OFL 1.1, Christian Thalmann) into compact outline data
// for the e-ink rasterizer. Run once: `node scripts/build-font.mjs`. Output is committed.
import opentype from 'opentype.js';
import { readFileSync, writeFileSync } from 'node:fs';

const CHARS = [...new Set(
  Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('') +
  '¡¿ÁÉÍÓÚÜÑáéíóúüñçÇàèìòùâêîôûäëïöÀÈÒ°·–—’‘“”…×ºª',
)];

function build(file) {
  const font = opentype.parse(readFileSync(new URL(`fonts/${file}`, import.meta.url)).buffer);
  const upm = font.unitsPerEm;
  const glyphs = {};
  for (const ch of CHARS) {
    const g = font.charToGlyph(ch);
    if (!g || (g.index === 0 && ch !== ' ')) continue;
    const parts = [];
    for (const c of g.path.commands) {
      const r = (v) => Math.round(v);
      if (c.type === 'M') parts.push('M', r(c.x), r(-c.y));
      else if (c.type === 'L') parts.push('L', r(c.x), r(-c.y));
      else if (c.type === 'Q') parts.push('Q', r(c.x1), r(-c.y1), r(c.x), r(-c.y));
      else if (c.type === 'C') parts.push('C', r(c.x1), r(-c.y1), r(c.x2), r(-c.y2), r(c.x), r(-c.y));
      else if (c.type === 'Z') parts.push('Z');
    }
    glyphs[ch] = [Math.round(g.advanceWidth), parts.join(' ')];
  }
  const kern = {};
  const letters = CHARS.filter((c) => /[\p{L}.,]/u.test(c));
  for (const a of letters) for (const b of letters) {
    const k = font.getKerningValue(font.charToGlyph(a), font.charToGlyph(b));
    if (k) kern[a + b] = k;
  }
  return { upm, capHeight: font.tables.os2.sCapHeight || 630, glyphs, kern };
}

const out = `// Cormorant Garamond outlines for the e-ink rasterizer. SIL Open Font License 1.1,
// (c) 2015 Christian Thalmann. Generated by scripts/build-font.mjs — do not edit by hand.
export const FONTS = ${JSON.stringify({
  regular: build('cormorant-0-500.ttf'),
  italic: build('cormorant-1-500.ttf'),
  caption: build('cormorant-0-600.ttf'),
})};
`;
writeFileSync(new URL('../web/lib/font-data.js', import.meta.url), out);
console.log(`font-data.js: ${(out.length / 1024).toFixed(0)} KB`);
